# Workflow for updating devdocs.mux.com with new documentation every time a new version is released
#
# Ths workflow assumes your releases are tagged either "vX.X.X" or "X.X.X", where X is a number of any length
#
# REQUIRED SECRETS:
#   AWS_DOCS_KEY
#   AWS_DOCS_SECRET
#   DOCS_REPO_PAT
# REQUIRED CONFIGURATION:
#  You have to change 'YOUR-LIB' to match a URL slug for your docs, like 'upload-swift' or 'data-avplayer'
name: Upload DocC DevDocs

on:
  push:
    branches: [ test-docs ]
  # release:
  #   types:
  #     - published

jobs:
  devdocs:
    runs-on: macos-latest
    name: Generate and Upload DocC Docs

    env:
      AWS_EC2_METADATA_DISABLED: true

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Checkout static devdocs repo
        uses: actions/checkout@v3
        with:
          repository: muxinc/mobile-sdk-dev-docs
          token: ${{ secrets.MOBILE_SDK_DEV_DOCS_CI_ACCESS_TOKEN }}
          path: docs-root
